### ISSUE TITLE
Wrong FOSOAuth user provider

### ISSUE THREAD

**Issue by qweluke** [zball/FOSREST-User-OAuth-Skeleton#4]
see:
https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2272

instead of

```
    service:
        user_provider: fos_user.user_manager
        options:
            supported_scopes: use
```

should be
```
    service:
        user_provider: fos_user.user_provider.username
        options:
            supported_scopes: use
```
